# initial
site_name: Smooth Soos
site_author: 'Shunhua Liu'
site_url: https://SHUASmooth.github.io/
copyright: Copyright © 2024 Shunhua Liu
# architecture
nav:
  - 首页: 
    - index.md
  - PERSONAL PARTICULARS:
    - 关于我: 个人/关于我.md
    - 荣誉: 个人/荣誉.md
    - 工作经历: 个人/工作经历.md
  - 学术:
    - 研究:
      - SRTP: 研究/SRTP.md
      - 其他: 研究/其他.md
      # - course:
  - 新闻:
    - 生活: 新闻/生活.md

theme:
  # initial
  name: material
  logo: images/logo.png
  # favicon: images/logo_TIGC_black_color.png
  # main color
  language: zh
  palette: 
    # Palette toggle for light mode
    - scheme: default
      primary: light green
      accent: pink
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: yellow
      accent: deep orange
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  
  features:
  # navigation
    - navigation.tabs
    - navigation.top
  # icons
  icon:
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16

extra_css:
  - css/extra.css
  - css/neoteroi-mkdocs.css
  
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
     
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - neoteroi.timeline
  - neoteroi.cards
  # icron
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

# language    

extra:
  alternate:
    - name: English
      link: /en/
      lang: en
    - name: Chinese
      link: /zh/
      lang: zh
